---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        clang_version: [latest, 17, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Test Dockerfile
        run: cd test && docker build -t test_action:latest -f Dockerfile.test .

      - name: Run Test Dockerfile
        run: docker run --rm -e CLANG_VERSION=${{ matrix.clang_version }} test_action:latest
...
